//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Acteur = new HashSet<Acteur>();
        }
    
        public int FilmID { get; set; }
        public string IMDBnummer { get; set; }
        public string Naam { get; set; }
        public string AndereNaam { get; set; }
        public string Versie { get; set; }
        public string AantalDisks { get; set; }
        public string Jaar { get; set; }
        public string Land { get; set; }
        public string Speelduur { get; set; }
        public string Kijkwijzer { get; set; }
        public string Gezien { get; set; }
        public string Wenslijst { get; set; }
        public string InBezit { get; set; }
        public string Kleur { get; set; }
        public string ZW { get; set; }
        public string KleurZW { get; set; }
        public string Toegevoegd { get; set; }
        public string Serie { get; set; }
        public string DrieD { get; set; }
        public string Verhaal { get; set; }
        public string IMDBRate { get; set; }
        public string PersRate { get; set; }
        public string Afbeelding { get; set; }
        public string KijkwijzerKlasse { get; set; }
        public string Taalnaam { get; set; }
        public string GenreNaam { get; set; }
        public int RegisseurRegID { get; set; }
    
        public virtual Regisseur Regisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acteur> Acteur { get; set; }
    }
}
